// <auto-generated />
namespace WebApi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201302022333390_addedProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
